const BASE_URL = import.meta.env.VITE_API_BASE_URL;
const DOMAIN_NAME = import.meta.env.VITE_API_DOMAIN_NAME;
export const api = DOMAIN_NAME
const baseApi = BASE_URL
export const bannerApi = `${baseApi}/banner`;
export const serviceListApi = `${baseApi}/services`;
export const productListApi = `${baseApi}/products`;
export const faqDataApi = `${baseApi}/faqs`;
export const testimonialsApi = `${baseApi}/testimonials `;
export const teammembers = `${baseApi}/team-members  `;